### PR TITLE
Updates to the build process

### PR DESCRIPTION
**Pull request by altermarkive**
## Description:

Hi, would you be interested in a pull request? I was recently in need of a `nebula` container, found yours and updated a couple of things:

* Changed from https://github.com/crazy-max/ghaction-docker-buildx to https://github.com/docker/setup-buildx-action (the former is discontinued with the latter gaining traction) and started using https://github.com/docker/build-push-action (results in a more readable step config)
* Replaced the Docker login step with https://github.com/docker/login-action (it also handles clearing of the credentials automatically - regardless of the outcome of the steps following it)
* Switched to using QEMU (https://github.com/docker/setup-qemu-action) for cross-platform builds, which allowed me to skip using `tonistiigi/xx:golang`
* Updated from Go 1.14 to 1.16, which made the container slightly smaller
* Added a (separate) `nebula-cert` container, mostly to ease getting the right executable
* Skipped `gcc` & `make` packages (since they're included under `build-base`)
* Squashed one git warning (with `-c advice.detachedHead=false`)

I'm happy to give you more info if you like.

## Benefits of this PR and context:

Since some of the build pipeline actions were discontinued it makes sense to replace them with ones backed by an org and a growing community - it should ensure operational continuity of the builds for any future nebula releases.

## How Has This Been Tested?

Using (amd64 image) in production in a lab environment didn't surface any issues (neither related to runtime stability nor to config compatibility).

## Source / References

https://github.com/docker/login-action
https://github.com/docker/setup-qemu-action
https://github.com/docker/setup-buildx-action
https://github.com/docker/build-push-action

### CODE REVIEW

**Review by matthewgall — APPROVED** [review]
LGTM. Thanks for your contribution, appreciated!

**Review by matthewgall — APPROVED** [review]

**Comment by marek-burza** [comment]
Awesome! I'm happy I could contribute - thank you for your work on the Docker image for nebula!

Not sure why the check doesn't get ticked off:
image

I'll leave it up to you to merge/close the PR, if that's okay?

**Comment by matthewgall** [comment]
Apologies for the delay, managed to fix the build issue. Again, thanks for your contribution!

**Comment by marek-burza** [comment]
@matthewgall - no need to apologize at all - we all have our personal lives of course :)
I was only worried that I might have messed up something by changing my GitHub Actions config midflight.
I'm happy I could contribute and you accepted my PR! :)

**Comment by marek-burza** [comment]
@matthewgall I did goof though - apologies failing to notice it sooner - fixed it in https://github.com/buildsociety/nebula/pull/7

**Pull request merged**
